[build]
dockerfilePath = "docker/Dockerfile"
dockerContext = "."
dockerTarget = "production"
buildArgs = { CACHE_BUST = "2" }

[deploy]
startCommand = "npx prisma migrate deploy && node dist/main"
healthcheckPath = "/docs"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
